name: On release

on:
  release:
    types: [created]

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Check out commit
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          registry-url: https://registry.npmjs.org

      - name: Lint codebase
        run: npm run lint-codebase

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
