# Workflow only meant to be manually run to test the `lint-codebase` command
name: Test lint-codebase

on:
  workflow_dispatch:

jobs:
  test-lint-codebase-command:
    runs-on: ubuntu-latest

    steps:
      - name: Check out commit
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Lint codebase
        run: pnpm lint-codebase
